### PR TITLE
Display trento version UI

### PR DESCRIPTION
**Pull request by fabriziosestito**
Added the trento version to the UI.
Had to move the Version injected variable to a separate package (was in `cmd` before).
Version links to the github release, only the tag is displayed (without `+git.yabba.yabba`) for UX reasons (text was too long, looks bad).

### CODE REVIEW

**Comment by arbulu89** [comment]
Hi @fabriziosestito ,
Without doing any review, a screenshot would be appreciated (as far as I can see, the version comes in the sidebar, so we should take care of the collapsed and not collapsed options)

**Comment by fabriziosestito** [comment]
> Hi @fabriziosestito ,
> Without doing any review, a screenshot would be appreciated (as far as I can see, the version comes in the sidebar, so we should take care of the collapsed and not collapsed options)

@arbulu89 
image

image

**Comment by fabriziosestito** [comment]
@arbulu89 
image

image

**Review by arbulu89 — DISMISSED** [review]
Thanks @fabriziosestito ,
The code looks good.
In the other hand, I'm not that convinced of the output in the web, it looks a bit out of place (sepcially in the collapsed sidebar).
I think it is worthy to comment this with the UX team.
What do you thin @en3sis ?

**Comment by fabriziosestito** [comment]
@arbulu89
Yes you are right.
Also, i find a bit weird that the collapsed menu shows the full footer while the expanded menu shows the collapsed one.

**Comment by arbulu89** [comment]
> @arbulu89
> Yes you are right.
> Also, i find a bit weird that the collapsed menu shows the full footer while the expanded menu shows the collapsed one.

This was inherited from the 1st blue-horizon implementation.
We can change it. Let's wait to see what UX proposes.
Maybe just adding some icon to the version output in the sidebar option would make things more coherent, but I don't know it this is a good practice

**Comment by en3sis** [comment]
> Thanks @fabriziosestito ,
> The code looks good.
> In the other hand, I'm not that convinced of the output in the web, it looks a bit out of place (sepcially in the collapsed sidebar).
> I think it is worthy to comment this with the UX team.
> What do you thin @en3sis ?

Hey!

If all the information has to be visible (2nd screenshot) you could use only the page footer and not the menu one at all =D
You can refer to https://productbrand.suse.com/layout/footer for more information (and please let me know if any of that information it's confusing or it's not clear so we can re-visit and improve it)

**Comment by fabriziosestito** [comment]
@arbulu89 @en3sis I think we should go just with the extended footer (second screenshot), as it looks better imho.
Where would you position the version?

**Comment by arbulu89** [comment]
> @arbulu89 @en3sis I think we should go just with the extended footer (second screenshot), as it looks better imho.
> Where would you position the version?

Agree. I would only put it in the extended footer, and I like it personally the location and the way it looks

**Review by rtorrero — APPROVED** [review]
LGTM @fabriziosestito, thanks!

**Review by arbulu89 — APPROVED** [review]

**Pull request merged**
