### PR TITLE
Remove premium checks and their variables

### PR DESCRIPTION
**Pull request by arbulu89**
Remove the premium checks as we already have the `Premium` containers and code in place.

@stefanotorresi @lee-martin Is this the good moment to do this?

### CODE REVIEW

**Comment by stefanotorresi** [comment]
Hmm, I'd like to have the premium version running in the demo environment first.

**Comment by arbulu89** [comment]
> Hmm, I'd like to have the premium version running in the demo environment first.

Are we sure we want to have the `Premium` version on demo? It would expose already all the code

**Comment by stefanotorresi** [comment]
> > Hmm, I'd like to have the premium version running in the demo environment first.
> 
> Are we sure we want to have the `Premium` version on demo? It would expose already all the code

Good question, let me ask upwards. I would personally go for it regardless, but maybe we need to remove the implementation from the catalog.

**Comment by stefanotorresi** [comment]
All right, we can keep the demo as it is. No worries. Go forward with the latest list of premium checks we got from Diego.

**Comment by arbulu89** [comment]
@stefanotorresi New changes based on the list provided by @diegoakechi done

**Review by stefanotorresi — APPROVED** [review]

**Pull request merged**
