### PR TITLE
Adds an updated version of Trento Architecture Diagram

### PR DESCRIPTION
**Pull request by nelsonkopliku**
Added a Diagram that shows current Trento Architecture

### CODE REVIEW

**Review by dottorblaster — APPROVED** [review]
LGTM

**Comment by ajaeger** [comment]
You include a PNG - did you edit that directly or what is your source file? Would be great to include a source file to allow others to make changes to it.

**Review by arbulu89 — CHANGES_REQUESTED** [review]
Some comments:

- The runner uses the consul server as well, to get the available nodes and KV data in order to create the ansible inventory file. Maybe it is a bit overkill to add these small details, but it would be good
- The `DRBD` and `Other` machines are not really part of the SAP system itself (even though they are part of the deployment). A SAP system only consists of SAP application machines and HANA machines (and this 2nd is even argued). I would put them outside, as machines that I want to monitor but don't belong to a SAP system
- In order to make the naming most generic, I recommend the next. :
    - `hana01 -> hana primary`
    - `hana02 -> hana secondary`
    - `netweaver01 -> netweaver ascs`
    - `netweaver02 -> netweaver ers`
    - `other host -> netweaver pas`
    - `other host -> netweaver aas`

- I would rename `SAP Netweaver HA Cluster` to `SAP S4/HANA or Netweaver HA Cluster`

And outside the diagram comments.
The architecture page has many leftovers... `SAP Landscape` and `SAP Environment` are not used anymore.

I think that we should adapt the README wording to the new diagram so we don't create more confussion

**Comment by nelsonkopliku** [comment]
Thanks @arbulu89 for the review!

> The runner uses the consul server as well, to get the available nodes and KV data in order to create the ansible inventory file. Maybe it is a bit overkill to add these small details, but it would be good

Added

> The `DRBD` and `Other` machines are not really part of the SAP system itself (even though they are part of the deployment). A SAP system only consists of SAP application machines and HANA machines (and this 2nd is even argued). I would put them outside, as machines that I want to monitor but don't belong to a SAP system

Moved outside in `SAP Deployment`

> In order to make the naming most generic, I recommend the next. :
>   
>   * `hana01 -> hana primary`
>   * `hana02 -> hana secondary`
>   * `netweaver01 -> netweaver ascs`
>   * `netweaver02 -> netweaver ers`
>   * `other host -> netweaver pas`
>   * `other host -> netweaver aas`
>   * I would rename `SAP Netweaver HA Cluster` to `SAP S4/HANA or Netweaver HA Cluster`

Names changed as suggested

> And outside the diagram comments. The architecture page has many leftovers... `SAP Landscape` and `SAP Environment` are not used anymore.
> 
> I think that we should adapt the README wording to the new diagram so we don't create more confussion
For this one: I see your point of not creating too much confusion, and I agree. I would just not change what you suggest yet, because I'd feel uncomfortable.

To me  `SAP Landscape` and `SAP Environment` are quite important concepts to keep in mind because that's what the naming is in SAP world and I would not remove reference to those.

What would be indeed interesting to me is add a representation for that. For instance:

trento-architecture drawio (3)

**Comment by nelsonkopliku** [comment]
> You include a PNG - did you edit that directly or what is your source file? Would be great to include a source file to allow others to make changes to it.

Good point! Thank you. 
I now added the `.svg` file which should be somehow editable.

Hope this helps.

**Review by dottorblaster — APPROVED** [review]
Before it was LGTM, now it's super-LGTM!

**Comment by arbulu89** [comment]
> Thanks @arbulu89 for the review!
> 
> > The runner uses the consul server as well, to get the available nodes and KV data in order to create the ansible inventory file. Maybe it is a bit overkill to add these small details, but it would be good
> 
> Added
> 
> > The `DRBD` and `Other` machines are not really part of the SAP system itself (even though they are part of the deployment). A SAP system only consists of SAP application machines and HANA machines (and this 2nd is even argued). I would put them outside, as machines that I want to monitor but don't belong to a SAP system
> 
> Moved outside in `SAP Deployment`
> 
> > In order to make the naming most generic, I recommend the next. :
> > 
> > * `hana01 -> hana primary`
> > * `hana02 -> hana secondary`
> > * `netweaver01 -> netweaver ascs`
> > * `netweaver02 -> netweaver ers`
> > * `other host -> netweaver pas`
> > * `other host -> netweaver aas`
> > * I would rename `SAP Netweaver HA Cluster` to `SAP S4/HANA or Netweaver HA Cluster`
> 
> Names changed as suggested
> 
> > And outside the diagram comments. The architecture page has many leftovers... `SAP Landscape` and `SAP Environment` are not used anymore.
> > I think that we should adapt the README wording to the new diagram so we don't create more confussion
> 
> For this one: I see your point of not creating too much confusion, and I agree. I would just not change what you suggest yet, because I'd feel uncomfortable.
> 
> To me `SAP Landscape` and `SAP Environment` are quite important concepts to keep in mind because that's what the naming is in SAP world and I would not remove reference to those.
> 

The thing is that we had these terms there because they were in the architecture image. And because Trento was used these exact names in the web app. Now, we have removed them and they are not visible anymore.
If any user wants to group the machines/cluster within this group, this is their call, but not part of the Trento.

That's why I would remove them. Users have tags now, so they can group in any type they want. Having the `Landscapes` and `Environments` entries here is a leftover in my opinion.

**Comment by nelsonkopliku** [comment]
> The thing is that we had these terms there because they were in the architecture image. And because Trento was used these exact names in the web app. Now, we have removed them and they are not visible anymore.
> If any user wants to group the machines/cluster within this group, this is their call, but not part of the Trento.
> 
> That's why I would remove them. Users have tags now, so they can group in any type they want. Having the Landscapes and Environments entries here is a leftover in my opinion.

@arbulu89 Ok, makes sense. Removed.

**Review by arbulu89 — APPROVED** [review]
@nelsonkopliku Re-reviewed!
Looks great now!
Green light!

**Pull request merged**
