### PR TITLE
Add provider field in the cloud details section

### PR DESCRIPTION
**Pull request by arbulu89**
Add the provider field in the cloud details:

image

### CODE REVIEW

**Review by dottorblaster — APPROVED** [review]
Not bad, do we want to capitalize the string?

**Comment by arbulu89** [comment]
> Not bad, do we want to capitalize the string?

The other remaining providers would by acronyms most probably.
We could put:
- Azure
- AWS
- GCP
Would this be better?

**Comment by dottorblaster** [comment]
Yeah I like this @arbulu89 :smile:

**Comment by arbulu89** [comment]
@dottorblaster 
Changes done in: https://github.com/trento-project/trento/pull/711/commits/d2943d14f3879ed0b287838b8c5b5b006e636eab
image

**Review by dottorblaster — APPROVED** [review]
LGTM

**Pull request merged**
