### PR TITLE
Remove /api prefix from swagger api docstrings

### PR DESCRIPTION
**Pull request by arbulu89**
Fix for: https://github.com/trento-project/trento/issues/453

I guess the error was introduced in: https://github.com/trento-project/trento/pull/411

PD: I don't know why it has introduced the `github.com/alecthomas/template"` package honestly. I'm using the swag:
```
trento> swag --version
swag version v1.7.0
```

### CODE REVIEW

**Review by nelsonkopliku — APPROVED** [review]
:+1:

**Comment by fabriziosestito** [comment]
package honestly. I'm using the swag:
> 
> ```
> trento> swag --version
> swag version v1.7.0
> ```

@arbulu89  swag should be pinned for everyone to 1.7.4 by the `tools/tools.go` package, could you confirm that installing it when cwd in trento repository root installs the above?

**Review by fabriziosestito — CHANGES_REQUESTED** [review]
package honestly. I'm using the swag:
> 
> ```
> trento> swag --version
> swag version v1.7.0
> ```

@arbulu89  swag should be pinned for everyone to 1.7.4 by the `tools/tools.go` package, could you confirm that installing it when cwd in trento repository root installs the above?

I tried to run the generation and with the pinned version the file differs, and the `"github.com/alecthomas/template"` is not there anymore.


EDIT: I also tried to access `/api/doc/index.html` on the main branch build, and it works correctly, so maybe something related to the `swag` version mismatch?

**Comment by nelsonkopliku** [comment]
> package honestly. I'm using the swag:
> 
> > ```
> > trento> swag --version
> > swag version v1.7.0
> > ```
> 
> @arbulu89 swag should be pinned for everyone to 1.7.4 by the `tools/tools.go` package, could you confirm that installing it when cwd in trento repository root installs the above?
> 
> I tried to run the generation and with the pinned version the file differs, and the `"github.com/alecthomas/template"` is not there anymore.
> 
> EDIT: I also tried to access `/api/doc/index.html` on the main branch build, and it works correctly, so maybe something related to the `swag` version mismatch?
>

Agreed on the version, if we can pin, that helps.

I also tried this http://demo.trento-project.io/api/docs/index.html#/default/get_api_checks_catalog and the problem I think is not the page itself, but the specific APIs execution from the Swagger UI that. breaks

image

**Comment by stefanotorresi** [comment]
ok, so there are multiple things to note here:
- Xabi is using an outdated version of swag. Re-running `go install github.com/swaggo/swag/cmd/swag`.
- #411 added this: https://github.com/trento-project/trento/blob/93bf0eb1188853d2d33450cf7da685726fdcd68f/web/api.go#L20 without removing `/api` from all the endpoints, so it's effectively duplicated.

The ideal solution would be to search and remove `/api` prefix from all the endpoint paths, and let the global `basePath` apply.

**Comment by fabriziosestito** [comment]
> Agreed on the version, if we can pin, that helps.

Version is already pinned, running `go install github.com/swaggo/swag/cmd/swag` in the root of the repository should do the work. 

> I also tried this http://demo.trento-project.io/api/docs/index.html#/default/get_api_checks_catalog and the problem I think is not the page itself, but the specific APIs execution from the Swagger UI that. breaks
> 

Ah alright I see now

**Comment by arbulu89** [comment]
Thanks @nelsonkopliku @stefanotorresi and @fabriziosestito ,
`swag` updated to the correct version. Now everything looks fine.

**Review by fabriziosestito — APPROVED** [review]

**Pull request merged**
