### PR TITLE
More helm configuration settings + testing

### PR DESCRIPTION
**Pull request by stefanotorresi**
this PR adds the following:

- `global.logLevel` Helm value
- `trento-runner.checkIntervalMins` Helm value
- `dependencies` Helm value map in each subchart so that service names and ports are no longer hardcoded, which was causing troubles for example when using the `nameOverride` value in any of the chart.
- a very fancy github action to lint the helm charts. (I tried also the installation and smoke testing, but I banged my head for hours on it and couldn't make it work)
- custom log handler for gin, to distinguish between the collector and the web gin instances
- ping endpoint to the collector gin instance, which concurred to fix `helm test` by using and endpoint that can respond with a 200 response to a simple GET

@fabriziosestito I tried to use Helm `global` values as you suggested, but then I found myself in a rabbit hole of overrides and template macros that I eventually have been defeated by. The hereby suggested approach deliberately keeps the consuming side and the service definition side separated: yes, it means parameters need to be changed in multiple places, but at least it's easy to understand.

Example new logger output:
```
time="2021-11-05 14:14:15" level=info msg="Starting web server"
time="2021-11-05 14:14:15" level=info msg="Starting collector server"
time="2021-11-05 14:14:15" level=info msg="Starting projector pool. Workers limit: 100"
time="2021-11-05 14:14:15" level=info msg="HTTP request" client=10.42.1.1 instance=public latency="80.629µs" method=GET status=200 uri=/api/ping user_agent=kube-probe/1.21
time="2021-11-05 14:14:21" level=info msg="HTTP request" client=10.42.1.1 instance=public latency="72.643µs" method=GET status=200 uri=/api/ping user_agent=kube-probe/1.21
time="2021-11-05 14:14:21" level=info msg="HTTP request" client=10.42.1.1 instance=public latency="107.103µs" method=GET status=200 uri=/api/ping user_agent=kube-probe/1.21
time="2021-11-05 14:14:25" level=info msg="HTTP request" client=10.42.1.14 instance=public latency="54.945µs" method=GET status=200 uri=/api/ping user_agent=Go-http-client/1.1
time="2021-11-05 14:14:31" level=info msg="HTTP request" client=10.42.1.1 instance=public latency="30.255µs" method=GET status=200 uri=/api/ping user_agent=kube-probe/1.21
time="2021-11-05 14:14:31" level=info msg="HTTP request" client=10.42.1.1 instance=public latency="19.616µs" method=GET status=200 uri=/api/ping user_agent=kube-probe/1.21
time="2021-11-05 14:14:31" level=info msg="HTTP request" client=10.42.1.14 instance=public latency=46.534925ms method=PUT status=200 uri=/api/checks/catalog user_agent=ansible-httpget
time="2021-11-05 14:14:41" level=info msg="HTTP request" client=10.42.1.1 instance=public latency="82.667µs" method=GET status=200 uri=/api/ping user_agent=kube-probe/1.21
time="2021-11-05 14:14:41" level=info msg="HTTP request" client=10.42.1.1 instance=public latency="96.074µs" method=GET status=200 uri=/api/ping user_agent=kube-probe/1.21
time="2021-11-05 14:14:51" level=info msg="HTTP request" client=10.42.1.1 instance=public latency="72.241µs" method=GET status=200 uri=/api/ping user_agent=kube-probe/1.21
time="2021-11-05 14:14:51" level=info msg="HTTP request" client=10.42.1.1 instance=public latency="81.088µs" method=GET status=200 uri=/api/ping user_agent=kube-probe/1.21
time="2021-11-05 14:15:01" level=info msg="HTTP request" client=10.42.1.1 instance=public latency="60.746µs" method=GET status=200 uri=/api/ping user_agent=kube-probe/1.21
time="2021-11-05 14:15:01" level=info msg="HTTP request" client=10.42.1.1 instance=public latency="74.233µs" method=GET status=200 uri=/api/ping user_agent=kube-probe/1.21
time="2021-11-05 14:15:11" level=info msg="HTTP request" client=10.42.1.1 instance=public latency="88.143µs" method=GET status=200 uri=/api/ping user_agent=kube-probe/1.21
time="2021-11-05 14:15:11" level=info msg="HTTP request" client=10.42.1.1 instance=public latency="56.635µs" method=GET status=200 uri=/api/ping user_agent=kube-probe/1.21
time="2021-11-05 14:15:21" level=info msg="HTTP request" client=10.42.1.1 instance=public latency="23.121µs" method=GET status=200 uri=/api/ping user_agent=kube-probe/1.21
time="2021-11-05 14:15:21" level=info msg="HTTP request" client=10.42.1.1 instance=public latency="21.827µs" method=GET status=200 uri=/api/ping user_agent=kube-probe/1.21
time="2021-11-05 14:15:25" level=info msg="HTTP request" client=10.42.1.21 instance=internal latency="38.809µs" method=GET status=200 uri=/api/ping user_agent=Wget
time="2021-11-05 14:15:27" level=info msg="HTTP request" client=10.42.0.31 instance=public latency="977.672µs" method=GET status=200 uri=/ user_agent=Wget
time="2021-11-05 14:15:31" level=info msg="HTTP request" client=10.42.1.1 instance=public latency="37.842µs" method=GET status=200 uri=/api/ping user_agent=kube-probe/1.21
```

### CODE REVIEW

**Comment by stefanotorresi** [comment]
WIP! It's late and I need beer.

**Comment by dottorblaster** [comment]
@stefanotorresi wow, it's 22, you need MOAR beers and rest!

**Review by dottorblaster — APPROVED** [review]
If the CI is happy I am happy as well

**Review by nelsonkopliku — APPROVED** [review]
Thanks! The helm setup looks more flexible now! :rocket:

**Review by fabriziosestito — APPROVED** [review]
LGTM! This is great!

**Pull request merged**
