### PR TITLE
Add load config to install-server script

### PR DESCRIPTION
**Pull request by fabriziosestito**
This PR adds the possibility to configure the server installer script by a `/etc/trento/installer.conf` file, by overriding env variables.
This is needed in order change the behavior of the installer script in different trento flavors (e.g. Premium)

### CODE REVIEW

**Review by nelsonkopliku — APPROVED** [review]
LGTM

If I understand correctly in `/etc/trento/installer.conf` we can override any of the env variable for the installer script.
For instance the place where to get the helm chart from, thus allowing the premium installation to get helm charts from a non IBS place.

:+1:

**Review by arbulu89 — APPROVED** [review]
Do you have some example of the `installer.conf` file?
I guess that it specially matters the `trento_chart_path` variable for this case, right?

**Review by dottorblaster — APPROVED** [review]
Cool :0

**Comment by fabriziosestito** [comment]
> Do you have some example of the `installer.conf` file? I guess that it specially matters the `trento_chart_path` variable for this case, right?

@arbulu89 sent you an example on slack

**Pull request merged**
