### PR TITLE
Added scrollbars to the codeblocks

### LINKED ISSUE #365: Check Catalog code blocks overflow too much and break the collapsable UX
As soon as a user expands a check with a big code block, the collapsable toggle gets pushed too far right and it needs a whole lot of scrolling before being able to interact with it with again.

Peek 2021-10-21 13-11

We should probably have overflow scroll bars around the code blocks, instead of the whole collapsable section.

### PR DESCRIPTION
**Pull request by MMuschner**
By adding scrollbars to the codeblocks, both verticaly and
horizontialy, the checks catalog should be more comfortable to use.

fix #365

### CODE REVIEW

**Review by dottorblaster — COMMENTED** [review]
Thanks for the contribution, really appreciated!

Just a question, why the `max-height`?

**Comment by MMuschner** [comment]
I experimented a bit and thought it would fit
scrollbars
.

**Review by dottorblaster — APPROVED** [review]
@MMuschner good job! LGTM

**Review by arbulu89 — COMMENTED** [review]
@MMuschner @dottorblaster 
It looks nice! Maybe it would be better to create a new class with these styles, to avoid styling all the `pre` tags. Maybe by now we don't have others, but it would help to reduce issues in the future.

By the way, thank you for adding the gif!!!

**Comment by dottorblaster** [comment]
@arbulu89 I actually agree but it's inside the `.ha-check-remediation` block, so the rule applies only in that context. Do you prefer to have a whole new class for that?

**Comment by arbulu89** [comment]
> @arbulu89 I actually agree but it's inside the `.ha-check-remediation` block, so the rule applies only in that context. Do you prefer to have a whole new class for that?

@dottorblaster I didn't check that hehe
No, it is fine this way. Thanks @dottorblaster

**Review by arbulu89 — APPROVED** [review]

**Review by nelsonkopliku — APPROVED** [review]

**Pull request merged**
