### PR TITLE
Remove hardcoded SID prefix (prd) from attributes keys

### PR DESCRIPTION
**Pull request by fabriziosestito**
Fixes broken attribute fetching when `SID != "PRD"`

### CODE REVIEW

**Review by arbulu89 — CHANGES_REQUESTED** [review]
@fabriziosestito There are still some changes required in (2 entries at least): https://github.com/trento-project/trento/blob/main/web/templates/cluster_hana.html.tmpl

For example: https://github.com/trento-project/trento/blob/main/web/templates/cluster_hana.html.tmpl#L31

**Comment by fabriziosestito** [comment]
> @fabriziosestito There are still some changes required in (2 entries at least): https://github.com/trento-project/trento/blob/main/web/templates/cluster_hana.html.tmpl
> 
> For example: https://github.com/trento-project/trento/blob/main/web/templates/cluster_hana.html.tmpl#L31

Ah yes i realized, you were too fast to review!

**Review by arbulu89 — APPROVED** [review]
Now looks good!
In my workaround, I implemented the new 2 methods for the `Node` struct, as until now the data was always obtained from the 1st node. I guess it doesn't make much difference.

PD: Maybe we could wrap the `strings.ToLower` thing in a `Node` struct method, to not have it duplicated all over the place. Anyway, it doesn't make a major difference neither. Up to you!

**Review by arbulu89 — APPROVED** [review]
Great!

**Pull request merged**
