### PR TITLE
Adds feedback collector

### PR DESCRIPTION
**Pull request by nelsonkopliku**
Experiment proposal for feedback collection.
The **Report feedback** button allows the customer using trento to provide direct feedback.

What do you think? Should it be available only for Premium flavor? :thinking: 

image

image

### CODE REVIEW

**Review by stefanotorresi — CHANGES_REQUESTED** [review]
My 2 cents:

- This is certainly in scope and would be a great addition! Although in our backlog this was not exactly planned for now. 😛 
- The styling _must_ be customized to make it consistent with the rest of the design system.
- SUSE has customer support system, and we have support teams who are responsible for handling user feedback. Do we really want to completely bypass that and put ourselves in the first line? Other products have a similar functionality which probably hooks to SUSE service desk instead of Jira directly.
- Ask the SUMA team if and how are they doing such a thing. I'd be surprised if they didn't have something similar.

**Comment by stefanotorresi** [comment]
more feedback from Diego:
- we should make _very_ clear for the user that this feature must not be used for issuing enterprise support requests, just ideas and feedback for which there is no contract obligation like SLAs and such.

**Comment by arbulu89** [comment]
@nelsonkopliku What is this actually doing? Or is it just the view itself?
And for more tactical questions:
- Do we have someone who will take care of the responses?
- The modal asks for `name/email`,etc. This would most probably require GPDR things, etc.

**Comment by nelsonkopliku** [comment]
> * This is certainly in scope and would be a great addition! Although in our backlog this was not exactly planned for now. stuck_out_tongue
>
Fair enough :smile: it's just been part of the boards spike, and it was pretty cheap, and i am not going to put much more effort on it :sweat_smile: 

> * The styling _must_ be customized to make it consistent with the rest of the design system.
>
How would you like it? Is this better?

image

**Comment by nelsonkopliku** [comment]
> What is this actually doing? Or is it just the view itself?
> 
it is a jira funcionality that allows you to embed feedback collection forms like this.
Whenever there's a submission of a feedback, it goes as an item in a dedicated backlog space that generates data.

> Do we have someone who will take care of the responses?
>
It does not necessarily need too frequent activity, yet regular even if not really frequent.
It'd be a way to collect feedbacks more directly from who is using Trento and try to understand the users.

> The modal asks for `name/email`,etc. This would most probably require GPDR things, etc.
> I would be careful with this implementation and only provide it once we have all the tactical/legal things answered
>
really good point. They are not required, yet I'd rather remove those, but I cannot actually find a way to do that :confused: 


It just came quite free when playing with jira backlog :sweat_smile:

**Comment by stefanotorresi** [comment]
Ok, so, before we merge this, we need to acknowledge that this implementation has a problem we can't solve now: the styling and structure of the form cannot be fully customized. This means we will have this feature with a completely different color palette and design language.
OTOH, I don't want to stall the feature because of this; after all, it is a very simple thing which could give us a lot of value, especially at this early stage of development.
While we could still merge this as is, before doing that I'd like us to acknowledge that we will sooner or later need to decommission this feature in favour of something similar with a properly integrated UI/UX.

**Comment by nelsonkopliku** [comment]
@stefanotorresi 
green again
image

I will create followup backlog item :wink:

**Comment by dottorblaster** [comment]
:shipit:

**Review by stefanotorresi — APPROVED** [review]

**Pull request merged**
