### PR TITLE
Goodbye ARA

### PR DESCRIPTION
**Pull request by arbulu89**
Remove any ARA leftover:
- Golang code from `cmd`, `runner` and `web` components
- Helm chart installation
- Github CI
- Dockerfile and python requirements
- Documentation

### CODE REVIEW

**Comment by fabriziosestito** [comment]
image
OMG ahha

**Comment by arbulu89** [comment]
> image OMG ahha

It was a mistake somehow...
I commited the `package-lock.json` file by accident. I don't know why github considered it was a removal... XD

**Review by nelsonkopliku — APPROVED** [review]
GOOOOO

**Review by fabriziosestito — APPROVED** [review]
LGTM

**Pull request merged**
