### PR TITLE
Detect aws and gcp clouds in the agent

### PR DESCRIPTION
**Pull request by arbulu89**
Add `AWS` and `GCP` clouds autodetection in the agent. This data will be used in the server side and sent in telemetry.

The code is based on `crmsh`, as we have been refining there (together with the cloud providers themselves) the cloud auto-detection: https://github.com/ClusterLabs/crmsh/blob/master/crmsh/utils.py#L2055

This is how it looks like;
AWS:
image
image

GCP:
image
image

### CODE REVIEW

**Review by nelsonkopliku — APPROVED** [review]
Super cool!

The bare metal variant is missing, yet this is already a great improvement and I think we can add that later.
Shall we track it so we do not forget?

**Comment by arbulu89** [comment]
> Super cool!
> 
> The bare metal variant is missing, yet this is already a great improvement and I think we can add that later. Shall we track it so we do not forget?

The baremetal thing is a shadowy thing. In our case, baremetal is everything that it is not in the cloud (yes, it is that generic). I don't know what kind of accuracy we need here, but from the beginning, the idea of this field was to detect the cloud itself, and everything that is not in our interest gets out.
So, the question actually is more to the stakeholders. What they expect to find here if the machines is not in `aws/gcp/azure`?

**Review by dottorblaster — APPROVED** [review]
LGTM, the bare metal thing can wait. @nelsonkopliku shall we open an issue for that with a specific question tag?

**Comment by lee-martin** [comment]
> > > Super cool!
> > > The bare metal variant is missing, yet this is already a great improvement and I think we can add that later. Shall we track it so we do not forget?
> > 
> > 
> > The baremetal thing is a shadowy thing. In our case, baremetal is everything that it is not in the cloud (yes, it is that generic). I don't know what kind of accuracy we need here, but from the beginning, the idea of this field was to detect the cloud itself, and everything that is not in our interest gets out. So, the question actually is more to the stakeholders. What they expect to find here if the machines is not in `aws/gcp/azure`?
> 
> @arbulu89 I see, let's then discuss with stakeholders

What about rewording "cloud provider" into "provider"? To be is would still sound correct to say aws/gcp/azure are "providers" (without the cloud word) and anything that is now known for now could be labelled "unknown".

Then in the future we could progressively add in new providers like "vmware", "kvm", "dell server", "lenovo server". Not forgetting other cloud providers over time as well.

Adding new providers can wait, but I guess we should fix the name of the field soon though.

**Comment by lee-martin** [comment]
@arbulu89  I validated the idea to rewording from "cloud provider" into "provider" as above, which they would like to have to make the field more flexible than cloud only. Can you please update at your convenience. (Sorry, forgot to mention you explicitly in my previous response).

**Comment by arbulu89** [comment]
> @arbulu89 I validated the idea to rewording from "cloud provider" into "provider" as above, which they would like to have to make the field more flexible than cloud only. Can you please update at your convenience. (Sorry, forgot to mention you explicitly in my previous response).

Of course we can!
Could you open a ticket with the request?
Thanks

**Comment by stefanotorresi** [comment]
issue collected in https://github.com/trento-project/telemetry/issues/14

**Pull request merged**
