### PR TITLE
Allow to override TARGET_USER

### PR DESCRIPTION
**Pull request by rtorrero**
A follow up to #60 to allow to override the default "root" user which is something that will very likely be needed.

### CODE REVIEW

**Comment by stefanotorresi** [comment]
@rtorrero you can do this much more succinctly by using `:-`
E.g.
```bash
TARGET_USER=${TARGET_USER:-"root"}
```

see https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Shell-Parameter-Expansion for more details

**Review by stefanotorresi — CHANGES_REQUESTED** [review]
@rtorrero you can do this much more succinctly by using `:-`
E.g.
```bash
TARGET_USER=${TARGET_USER:-"root"}
```

see https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Shell-Parameter-Expansion for more details

**Comment by stefanotorresi** [comment]
Oh, btw, I forgot to mention that if we're not using root then we need to use `sudo` when starting `trento agent`!

**Comment by rtorrero** [comment]
Yes, using parameter expansion seems much more elegant here. I've also added a $ADD_PARAMS with `sudo` when $TARGET_USER is not root. I belive that's the only place where it's required, right?

Let me know if it looks better and I'll squash it before merge

**Review by stefanotorresi — DISMISSED** [review]

**Comment by stefanotorresi** [comment]
Perfect! You can rebase and merge.

**Review by stefanotorresi — APPROVED** [review]

**Pull request merged**
