### PR TITLE
Add premium badge to the premium checks in catalog

### PR DESCRIPTION
**Pull request by arbulu89**
Add premium badge to the premium checks in the checks catalog.
**How to use**.
In order to make a check `Premium` we need to add the data in the its metadata. To do that we need to change the file `runner/ansible/roles/checks/my-check/defaults/main.tf` for the check, and include a `premium: True` in the file.
By default, the checks are not premium.

image

**Question**:
It only goes in the catalog by now. I can include it in the `Check selection` and `Checks results`. In the 1st one it gets pretty ugly, I would need to widen the whole modal (something I would do in any case). Should we add it in those places too?

### CODE REVIEW

**Review by rtorrero — APPROVED** [review]
Great idea, I like this. APPROVED!

**Review by fabriziosestito — APPROVED** [review]

**Review by dottorblaster — APPROVED** [review]
LGTM

**Comment by rtorrero** [comment]
As to your questions: I would add it in the other sections too, but the full "Premium" badge might be a bit too much for the modals. Instead, we could use colors (if we identify a color with Premium by establish already in the checks catalog, it might be easier for the user to understand it) or maybe we could add a prefix to the checks title, e.g.: `Premium: Test if corosync.conf files are identical across all nodes `

**Review by nelsonkopliku — APPROVED** [review]

**Comment by stefanotorresi** [comment]
The only thing I'm not convinced about this is the column where we're putting the badge.
Have you tried the description column instead of the id one?

**Comment by arbulu89** [comment]
> The only thing I'm not convinced about this is the column where we're putting the badge. Have you tried the description column instead of the id one?
> 
> @rtorrero Hmmm, I don't quite like the idea of adding it as text elsewhere. The visual clue should be the same everywhere, i.e. green badge.

Well, it would look like exactly as it looks now, just moving the badge XD
I don't have any preference. It doesn't look better or worst in my opinion

**Comment by arbulu89** [comment]
Hey @dottorblaster ,
Do you know any frontend trick to align the badge start width?
Now, as the chars length is not exactly the same, the badge is no perfectly aligned:
image

@stefanotorresi already propose me to use `pre`, but this completely changes the font which I don't like

**Comment by dottorblaster** [comment]
@arbulu89 yeah you could have two different spans with something like a max-width, shall we look into this in a second moment? I find this idea very valuable

**Comment by arbulu89** [comment]
@stefanotorresi @fabriziosestito @dottorblaster 
This is how it looks like if the badge goes in the description cell:
image

Does it look better?

**Comment by dottorblaster** [comment]
It does actually look better to me, maybe we could give it a try with the premium tag before the description, but we can try further in a second moment.

**Comment by arbulu89** [comment]
> It does actually look better to me, maybe we could give it a try with the premium tag before the description, but we can try further in a second moment.

This is how it looks like with the tag at the beginning:
image

**Comment by arbulu89** [comment]
Finally, merging the the badge in the [description column](https://github.com/trento-project/trento/pull/504#issuecomment-981374574), in the right side. We can change if needed in the future.

**Pull request merged**
