### PR TITLE
Add project logo to header

### PR DESCRIPTION
**Pull request by stefanotorresi**
Screenshot from 2021-06-11 18-27-45

Also removes the rendering of the header submenu if empty (which it is, atm), because it causes some problems on the smallest viewport size.

### CODE REVIEW

**Comment by dirkmueller** [comment]
I only see trento-agent.png used - what are all the other icons for that you added?

**Comment by en3sis** [comment]
According to[ our guidelines]( https://productbrand.suse.com/product-labels) SUSE products should not have any icons/illustration

> As we do not create product brands, we don’t apply logos for commercial products. We label them with their names, written in our corporate font Poppins and without any additional picture mark. As with any rule, there is one exception: SUSE Rancher

**Comment by en3sis** [comment]
Yes, the logo can be there! 

BTW maybe this could be a good moment to also add it as the websites `favicon` ?

**Comment by stefanotorresi** [comment]
> I only see trento-agent.png used - what are all the other icons for that you added?

hmm, I added those for potential future usage.

**Review by dirkmueller — APPROVED** [review]

**Pull request merged**
