### PR TITLE
follow official product guidelines

### PR DESCRIPTION
**Pull request by stefanotorresi**
change the copywrite a little and fix margin and html quoting. (never use `'`, always use `"`, we need a linter for this)

### CODE REVIEW

**Comment by stefanotorresi** [comment]
jeez we really need a proper html dom testing library.

**Review by arbulu89 — APPROVED** [review]
I would appreciate a screenshot of the update to see how it looks like

**Comment by stefanotorresi** [comment]
before:
Screenshot from 2021-12-17 11-34-14

after:
Screenshot from 2021-12-17 11-32-00

**Comment by arbulu89** [comment]
Thanks @stefanotorresi

**Pull request merged**
