### PR TITLE
Document the trento nomenclature

### PR DESCRIPTION
**Pull request by dirkmueller**
This adds some references to how Trento UI uses the various nomenclature.

### CODE REVIEW

**Review by stefanotorresi — APPROVED** [review]
LGTM!

**Review by stefanotorresi — CHANGES_REQUESTED** [review]
Actually, could we put this in a dedicated markdown file? :)

**Comment by dirkmueller** [comment]
@stefanotorresi I had it originally in a separate file, but the nomenclature makes total sense as a explanation of the architecture picture. do you agree?

**Review by stefanotorresi — APPROVED** [review]

**Comment by stefanotorresi** [comment]
fair enough!!

**Pull request merged**
