### PR TITLE
Add a --rolling option to the install-agent script to use factory repos

### PR DESCRIPTION
**Pull request by dottorblaster**
In the past week the team spotted the need for the installers to set up the latest RPM package coming from the Factory repository, so we're adding this to the `install-agent.sh` script. We'll do that in a further PR for the `install-server.sh` script too.

### CODE REVIEW

**Review by rtorrero — DISMISSED** [review]
Looks perfect to me :-)

**Review by arbulu89 — APPROVED** [review]
Looks good!

PD: For future (or current improvements)
As @stefanotorresi is trying to understand, could we even confirm if this KEY thing is needed, or we could get rid off it?

**Review by arbulu89 — CHANGES_REQUESTED** [review]
@dottorblaster We would need to add the new flag usage in the `-h` output

**Comment by dottorblaster** [comment]
@arbulu89 I updated the help text, thank you for reminding me :sweat_smile:

**Review by arbulu89 — APPROVED** [review]
Thanks!

**Pull request merged**
